"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var init_js_1 = require("./app/init.js");
var listen_js_1 = require("./app/listen.js");
var middlewares_js_1 = require("./app/middlewares.js");
var routes_js_1 = require("./app/routes.js");
var app = (0, express_1.default)();
(0, middlewares_js_1.default)(app);
await (0, init_js_1.default)();
app.use("/", routes_js_1.default);
(0, listen_js_1.default)(app);
