import { useState } from "react";
import {
  User,
  AtSign,
  Mail,
  KeyRound,
  Eye,
  EyeOff,
  ArrowRight,
  ShieldCheck,
  PawPrint,
  ChevronDown,
  Check,
} from "lucide-react";
import PolicyModal from "./PolicyModal";
import { useAppDispatch } from "../store/hooks";
import { loginSuccess } from "../store/slices/authSlice";
import { useRegisterUserMutation } from "../store/apiSlice";
import "./forms.css";
import "./Register.css";

interface Props {
  onNext: () => void;
  onToLogin: () => void;
}

// ── Policy content ────────────────────────────────────────────────────────────

const TC_CONTENT = (
  <>
    <h3>1. Acceptance of Terms</h3>
    <p>
      By creating a PawTrack account you agree to be bound by these Terms of
      Service and all applicable laws and regulations. If you do not agree, you
      may not use the service.
    </p>

    <h3>2. Use of the Service</h3>
    <p>
      PawTrack provides real-time pet health and location monitoring. You agree
      to use the service only for lawful purposes and in a way that does not
      infringe the rights of others.
    </p>
    <ul>
      <li>You must be at least 16 years old to create an account.</li>
      <li>
        You are responsible for maintaining the confidentiality of your account
        credentials.
      </li>
      <li>You may not share access with unauthorised users.</li>
    </ul>

    <h3>3. Device &amp; Data Accuracy</h3>
    <p>
      PawTrack collar sensors provide approximate health and location readings.
      Data should not replace professional veterinary advice. We are not liable
      for decisions made solely on sensor data.
    </p>

    <h3>4. Subscription &amp; Billing</h3>
    <p>
      Certain features require an active subscription. Fees are billed in
      advance and are non-refundable except as required by law. We reserve the
      right to modify pricing with 30 days&apos; notice.
    </p>

    <h3>5. Termination</h3>
    <p>
      We may suspend or terminate your account at any time if you violate these
      terms. You may delete your account at any time from your account settings.
    </p>

    <h3>6. Limitation of Liability</h3>
    <p>
      PawTrack is provided &quot;as is&quot;. To the fullest extent permitted by law, we
      disclaim all warranties and limit our liability to the amount you paid in
      the 12 months preceding any claim.
    </p>

    <h3>7. Changes to Terms</h3>
    <p>
      We may update these terms from time to time. Continued use of the service
      after changes constitutes your acceptance of the new terms.
    </p>
  </>
);

const PP_CONTENT = (
  <>
    <h3>1. Information We Collect</h3>
    <p>
      We collect information you provide directly (name, email, phone) and data
      generated by your PawTrack collar (GPS coordinates, heart rate,
      temperature, activity).
    </p>

    <h3>2. How We Use Your Information</h3>
    <ul>
      <li>Provide and improve the PawTrack service.</li>
      <li>Send health alerts and notifications about your pet.</li>
      <li>Analyse aggregate, anonymised usage patterns to improve features.</li>
      <li>Comply with legal obligations.</li>
    </ul>

    <h3>3. Data Sharing</h3>
    <p>
      We do not sell your personal data. We may share data with trusted service
      providers (e.g., cloud hosting, map providers) under strict
      confidentiality agreements. We may disclose data when required by law.
    </p>

    <h3>4. Data Retention</h3>
    <p>
      We retain your data for as long as your account is active. You may request
      deletion at any time; we will erase your data within 30 days, except where
      retention is required by law.
    </p>

    <h3>5. Security</h3>
    <p>
      We use industry-standard encryption (TLS in transit, AES-256 at rest) to
      protect your data. No system is 100% secure; please use a strong, unique
      password.
    </p>

    <h3>6. Your Rights</h3>
    <p>
      Depending on your jurisdiction you may have rights to access, correct,
      export, or delete your data. Contact <strong>privacy@pawtrack.app</strong>{" "}
      to exercise these rights.
    </p>

    <h3>7. Cookies</h3>
    <p>
      We use essential cookies to keep you logged in and preference cookies to
      remember your settings. We do not use advertising cookies.
    </p>

    <h3>8. Contact</h3>
    <p>
      Questions? Email us at <strong>privacy@pawtrack.app</strong> or write to
      PawTrack Ltd., Kathmandu, Nepal.
    </p>
  </>
);

// ── Component ─────────────────────────────────────────────────────────────────

export default function Register({ onNext, onToLogin }: Props) {
  const dispatch = useAppDispatch();
  const [registerUser, { isLoading }] = useRegisterUserMutation();

  // Form fields
  const [fullName,  setFullName]  = useState("");
  const [username,  setUsername]  = useState("");
  const [email,     setEmail]     = useState("");
  const [password,  setPassword]  = useState("");
  const [showPass,  setShowPass]  = useState(false);
  const [showConfirm, setShowConfirm] = useState(false);
  const [error,     setError]     = useState<string | null>(null);

  // Modal open state
  const [openTC, setOpenTC] = useState(false);
  const [openPP, setOpenPP] = useState(false);

  // Individual agree states
  const [agreedTC, setAgreedTC] = useState(false);
  const [agreedPP, setAgreedPP] = useState(false);

  const canSubmit = agreedTC && agreedPP;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!canSubmit) return;
    setError(null);
    try {
      const data = await registerUser({ username, email, password }).unwrap();
      dispatch(loginSuccess({ user: data.user, token: data.token }));
      onNext();
    } catch (err: unknown) {
      const msg = (err as { data?: { message?: string } })?.data?.message;
      setError(msg ?? "Registration failed — please try again");
    }
  };

  return (
    <div className="reg-page">
      <div className="reg-card">
        {/* Header */}
        <div className="reg-header">
          <div className="reg-logo-icon"><PawPrint size={28} strokeWidth={1.8} /></div>
          <h1>Create your account</h1>
          <p>Join PawTrack and keep your pet safe</p>
        </div>

        <form onSubmit={handleSubmit}>
          {/* Full name */}
          <div className="field">
            <label htmlFor="reg-name">Full name</label>
            <div className="input-wrap">
              <User size={15} className="field-icon" />
              <input
                id="reg-name"
                type="text"
                placeholder="Alex Johnson"
                value={fullName}
                onChange={e => setFullName(e.target.value)}
                required
              />
            </div>
          </div>
          {/* Username */}
          <div className="field">
            <label htmlFor="reg-username">Username</label>
            <div className="input-wrap">
              <AtSign size={15} className="field-icon" />
              <input
                id="reg-username"
                name="username"
                type="text"
                placeholder="pawtracker99"
                autoComplete="username"
                value={username}
                onChange={e => setUsername(e.target.value)}
                required
              />
            </div>
          </div>

          {/* Email */}
          <div className="field">
            <label htmlFor="reg-email">Email address</label>
            <div className="input-wrap">
              <Mail size={15} className="field-icon" />
              <input
                id="reg-email"
                type="email"
                placeholder="you@example.com"
                value={email}
                onChange={e => setEmail(e.target.value)}
                required
              />
            </div>
          </div>

          {/* Phone (optional) */}
          <div className="field">
            <label htmlFor="reg-phone">
              Phone number <span className="opt-badge">optional</span>
            </label>
            <div className="input-wrap">
              <ShieldCheck size={15} className="field-icon" />
              <input id="reg-phone" type="tel" placeholder="+977 98XXXXXXXX" />
            </div>
          </div>

          {/* Password */}
          <div className="field">
            <label htmlFor="reg-password">Password</label>
            <div className="input-wrap">
              <KeyRound size={15} className="field-icon" />
              <input
                id="reg-password"
                type={showPass ? "text" : "password"}
                placeholder="Min. 8 characters"
                value={password}
                onChange={e => setPassword(e.target.value)}
                required
              />
              <button
                type="button"
                className="pass-toggle"
                onClick={() => setShowPass((v) => !v)}
                aria-label={showPass ? "Hide password" : "Show password"}
              >
                {showPass ? <EyeOff size={15} /> : <Eye size={15} />}
              </button>
            </div>
          </div>

          {/* Confirm password */}
          <div className="field">
            <label htmlFor="reg-confirm">Confirm password</label>
            <div className="input-wrap">
              <KeyRound size={15} className="field-icon" />
              <input
                id="reg-confirm"
                type={showConfirm ? "text" : "password"}
                placeholder="Re-enter password"
                required
              />
              <button
                type="button"
                className="pass-toggle"
                onClick={() => setShowConfirm((v) => !v)}
                aria-label={showConfirm ? "Hide password" : "Show password"}
              >
                {showConfirm ? <EyeOff size={15} /> : <Eye size={15} />}
              </button>
            </div>
          </div>

          {/* Password strength */}
          <div className="pwd-strength">
            <div className="strength-bars">
              <span className="s-bar filled" />
              <span className="s-bar filled" />
              <span className="s-bar" />
              <span className="s-bar" />
            </div>
            <span className="strength-label">Fair</span>
          </div>

          {/* Policy rows */}
          <div className="policy-rows">
            <span className="section-label">Agreements required</span>

            <button
              type="button"
              className={`policy-row${agreedTC ? " agreed" : ""}`}
              onClick={() => setOpenTC(true)}
            >
              <div className="policy-row-left">
                <div className={`policy-check${agreedTC ? " done" : ""}`}>
                  {agreedTC ? <Check size={11} strokeWidth={3} /> : null}
                </div>
                <span>Terms of Service</span>
              </div>
              {agreedTC ? (
                <span className="policy-agreed-badge">Agreed</span>
              ) : (
                <ChevronDown size={16} className="policy-chevron" />
              )}
            </button>

            <button
              type="button"
              className={`policy-row${agreedPP ? " agreed" : ""}`}
              onClick={() => setOpenPP(true)}
            >
              <div className="policy-row-left">
                <div className={`policy-check${agreedPP ? " done" : ""}`}>
                  {agreedPP ? <Check size={11} strokeWidth={3} /> : null}
                </div>
                <span>Privacy Policy</span>
              </div>
              {agreedPP ? (
                <span className="policy-agreed-badge">Agreed</span>
              ) : (
                <ChevronDown size={16} className="policy-chevron" />
              )}
            </button>
          </div>

          {error && <p className="form-error">{error}</p>}

          <button
            type="submit"
            className="btn-primary full reg-submit"
            disabled={!canSubmit || isLoading}
          >
            {isLoading ? 'Creating account…' : <> Create account <ArrowRight size={15} /> </>}
          </button>
        </form>

        {/* Divider */}
        <div className="divider">
          <span>or sign up with</span>
        </div>

        <button className="btn-google" onClick={onNext}>
          <GoogleSVG />
          Continue with Google
        </button>

        <p className="signup-cta">
          Already have an account?{" "}
          <button type="button" className="link-btn" onClick={onToLogin}>
            Sign in
          </button>
        </p>
      </div>

      {/* Modals */}
      {openTC && (
        <PolicyModal
          title="Terms of Service"
          content={TC_CONTENT}
          agreed={agreedTC}
          onAgree={setAgreedTC}
          onClose={() => setOpenTC(false)}
        />
      )}
      {openPP && (
        <PolicyModal
          title="Privacy Policy"
          content={PP_CONTENT}
          agreed={agreedPP}
          onAgree={setAgreedPP}
          onClose={() => setOpenPP(false)}
        />
      )}
    </div>
  );
}

function GoogleSVG() {
  return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none">
      <path
        d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"
        fill="#4285F4"
      />
      <path
        d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"
        fill="#34A853"
      />
      <path
        d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l3.66-2.84z"
        fill="#FBBC05"
      />
      <path
        d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"
        fill="#EA4335"
      />
    </svg>
  );
}
